import 'package:hive/hive.dart';

part 'hive_models.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class HistoryItem extends HiveObject {
  @HiveField(0)
  final String word;

  @HiveField(1)
  final DateTime timestamp;

  HistoryItem({required this.word, required this.timestamp});
}

@HiveType(typeId: 1)
class FavoriteItem extends HiveObject {
  @HiveField(0)
  final String word;

  FavoriteItem({required this.word});
}
